package projekt.cloud.piece.c2pinyin.projekt.cloud.piece.c2pinyin

val CNCities = PinyinDictionary(
    PinyinMap("都兰", "DU", "LAN"),
    PinyinMap("柞水", "ZHA", "SHUI"),
    PinyinMap("六合", "LU", "HE"),
    PinyinMap("筠连", "JUN", "LIAN"),
    PinyinMap("江都", "JIANG", "DU"),
    PinyinMap("柏乡", "BAI", "XIANG"),
    PinyinMap("长阳", "CHANG", "YANG"),
    PinyinMap("长春", "CHANG", "CHUN"),
    PinyinMap("长白", "CHANG", "BAI"),
    PinyinMap("成都", "CHENG", "DU"),
    PinyinMap("闵行", "MIN", "HANG"),
    PinyinMap("新都", "XIN", "DU"),
    PinyinMap("天长", "TIAN", "CHANG"),
    PinyinMap("番禺", "PAN", "YU"),
    PinyinMap("都匀", "DU", "YUN"),
    PinyinMap("长垣", "CHANG", "YUAN"),
    PinyinMap("长治县", "CHANG", "ZHI", "XIAN"),
    PinyinMap("武都", "WU", "DU"),
    PinyinMap("沈丘", "CHEN", "QIU"),
    PinyinMap("温宿", "WEN", "XIU"),
    PinyinMap("蚌埠", "BENG", "BU"),
    PinyinMap("长顺", "CHANG", "SHUN"),
    PinyinMap("泌阳", "BI", "YANG"),
    PinyinMap("莘县", "SHEN", "XIAN"),
    PinyinMap("大埔", "DA", "BU"),
    PinyinMap("塔什库尔干", "TA", "SHI", "KU", "ER", "GAN"),
    PinyinMap("三都", "SAN", "DU"),
    PinyinMap("盐都", "YAN", "DU"),
    PinyinMap("子长", "ZI", "CHANG"),
    PinyinMap("于都", "YU", "DU"),
    PinyinMap("民乐", "MIN", "YUE"),
    PinyinMap("花都", "HUA", "DU"),
    PinyinMap("商都", "SHANG", "DU"),
    PinyinMap("都昌", "DU", "CHANG"),
    PinyinMap("克什克腾旗", "KE", "SHI", "KE", "TENG", "QI"),
    PinyinMap("延长", "YAN", "CHANG"),
    PinyinMap("长白山", "CHANG", "BAI", "SHAN"),
    PinyinMap("宁都", "NING", "DU"),
    PinyinMap("曾母暗沙", "ZENG", "MU", "AN", "SHA"),
    PinyinMap("南乐", "NAN", "YUE"),
    PinyinMap("长武", "CHANG", "WU"),
    PinyinMap("长宁", "CHANG", "NING"),
    PinyinMap("长安", "CHANG", "AN"),
    PinyinMap("重庆", "CHONG", "QING"),
    PinyinMap("行唐", "HANG", "TANG"),
    PinyinMap("伽师", "GA", "SHI"),
    PinyinMap("长寿", "CHANG", "SHOU"),
    PinyinMap("绥棱", "SUI", "LING"),
    PinyinMap("长汀", "CHANG", "TING"),
    PinyinMap("繁峙", "FAN", "SHI"),
    PinyinMap("长沙", "CHANG", "SHA"),
    PinyinMap("长岛", "CHANG", "DAO"),
    PinyinMap("厦门", "XIA", "MEN"),
    PinyinMap("长岭", "CHANG", "LING"),
    PinyinMap("长泰", "CHANG", "TAI"),
    PinyinMap("尉犁", "YU", "LI"),
    PinyinMap("六安", "LU", "AN"),
    PinyinMap("八宿", "BA", "XIU"),
    PinyinMap("长海", "CHANG", "HAI"),
    PinyinMap("牟平", "MU", "PING"),
    PinyinMap("阿图什", "A", "TU", "SHI"),
    PinyinMap("长治市", "CHANG", "ZHI", "SHI"),
    PinyinMap("长清", "CHANG", "QING"),
    PinyinMap("长丰", "CHANG", "FENG"),
    PinyinMap("长乐", "CHANG", "LE"),
    PinyinMap("丰都", "FENG", "DU"),
    PinyinMap("喀什", "KA", "SHI"),
    PinyinMap("桐柏", "TONG", "BAI"),
    PinyinMap("乐清", "YUE", "QING"),
    PinyinMap("中牟", "ZHONG", "MU"),
    PinyinMap("什邡", "SHI", "FANG"),
    PinyinMap("乌什", "WU", "SHI"),
    PinyinMap("都安", "DU", "AN"),
    PinyinMap("乐亭", "LAO", "TING"),
    PinyinMap("吴堡", "WU", "BU"),
    PinyinMap("那曲", "NA", "QU"),
    PinyinMap("单县", "SHAN", "XIAN"),
    PinyinMap("那坡", "NA", "PO"),
    PinyinMap("且末", "JU", "MO"),
    PinyinMap("长兴", "CHANG", "XING"),
    PinyinMap("弓长岭", "GONG", "CHANG", "LING"),
    PinyinMap("昌都", "CHANG", "DU"),
    PinyinMap("猇亭", "XIAO", "TING"),
    PinyinMap("涡阳", "GUO", "YANG"),
    PinyinMap("犍为", "QIAN", "WEI"),
    PinyinMap("望都", "WANG", "DU"),
    PinyinMap("略阳", "LUE", "YANG"),
    PinyinMap("双柏", "SHUANG", "BAI"),
    PinyinMap("长沙", "CHANG", "SHA"),
    PinyinMap("新乐", "XIN", "YUE"),
    PinyinMap("长葛", "CHANG", "GE"),
    PinyinMap("错那", "CUO", "NA"),
    PinyinMap("都江堰", "DU", "JIANG", "YAN"),
    PinyinMap("浪卡子", "LANG", "QIA", "ZI"),
    PinyinMap("荥阳", "XING", "YANG"),
    PinyinMap("碌曲", "LU", "QU"),
    PinyinMap("黄陂", "HUANG", "PI"),
)